version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: rotiseria_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rotiseria_pos
    ports:
      - "5433:5432"